# Generated by Django 3.0.7 on 2020-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
    ]
