# Generated by Django 3.0.7 on 2020-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
