# Generated by Django 3.0.7 on 2020-06-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experience_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototext',
            name='number',
            field=models.IntegerField(default=-1),
        ),
    ]
