# Generated by Django 3.0.7 on 2020-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_phototext_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
